### ISSUE TITLE
[BUG] Upvalue Dealer Combo

### ISSUE THREAD

**Issue by DuncanEll** [Qbox-project/qb-drugs#2]
**Describe the bug**
So i started trying out qbox today and i installed a fresh install of the recipe and i get this error on qb drugs , not sure whats causing it asthis is just a fresh install and i have not touched anything yet

**To Reproduce**
1. Fresh Install of the recipe
2. Load in 
3. Create character

**Expected behavior**
n/a

**Screenshots**
https://i.imgur.com/HhSRM2A.png

**Questions (please complete the following information):**
 - When you last updated: Fresh install today
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by BerkieBb** [comment]
#3 fixes this

**Comment by DuncanEll** [comment]
Thank you
